[phases.setup]
nixPkgs = ["python311", "python311Packages.pip", "nodejs-18_x"]
aptPkgs = ["libglib2.0-0", "libnss3", "libnspr4", "libatk1.0-0", "libatk-bridge2.0-0", "libcups2", "libdrm2", "libdbus-1-3", "libxcb1", "libxkbcommon0", "libx11-6", "libxcomposite1", "libxdamage1", "libxext6", "libxfixes3", "libxrandr2", "libgbm1", "libpango-1.0-0", "libcairo2", "libasound2t64"]

[phases.install]
cmds = [
  "python -m pip install -r requirements.txt",
  "python -m pip install playwright",
  "python -m playwright install firefox"
]

[start]
cmd = "uvicorn main:app --host 0.0.0.0 --port $PORT"
