[phases.setup]
nixPkgs = ["python311", "nodejs-18_x"]

[phases.install]
cmds = [
  "pip install -r requirements.txt",
  "playwright install --with-deps firefox"
]

[start]
cmd = "uvicorn main:app --host 0.0.0.0 --port $PORT"
